#!/usr/bin/env ruby
# This is the start script for all our scripts

require File.expand_path('../../config/setup',  __FILE__)
require File.expand_path('../../src/scripts/list_library_files',  __FILE__)
require File.expand_path('../../src/scripts/list_images',  __FILE__)

def usage
  puts "usage: start <DBNAME> <command> [optional parameters]"
  puts "      where <command> is one of"
  puts "         list_library_files"
  puts "         list_images"
end

arg_count = ARGV.length

if arg_count < 2
  usage
else
  db_name = ARGV[0]
  command = ARGV[1]
  command_args=ARGV[2, arg_count-2]

  ActiveRecord::Base.establish_connection(
    :adapter => 'sqlite3',
    :database => db_name
  )

  case command
  when 'list_library_files'
    ListLibraryFiles.run(command_args)
  when 'list_images'
    ListImages.run(command_args)
  else
    usage
  end
end
